image: python:3.10

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            caches:
              - pip
            script:
              - python -m pip install -U pip
              - python -m pip install -r requirements.txt
              - python -m pytest -q
        - step:
            name: Lint code
            script:
              - pip install flake8
              - flake8 . --extend-exclude=dist,build --show-source --statistics --ignore=E501,F401